### ISSUE TITLE
isset( $_SERVER['HTTP_X_HELPSCOUT_SIGNATURE'] ) check is too aggressive

### ISSUE THREAD

**Issue by pippinsplugins** [webzunft/edd-helpscout#12]
I was working on building another Help Scout integration today for my Restrict Content Pro plugin but was running into an issue where the app always returned the response from `EDD Help Scout`.

No matter what URL I used, EDD HS always took over.

Turns out this is because of the `isset( $_SERVER['HTTP_X_HELPSCOUT_SIGNATURE'] )` check in the `__construct()` method: https://github.com/dannyvankooten/edd-helpscout/blob/master/edd-helpscout.php#L64

Because of that, it's exceptionally difficult for another plugin to setup a HS response.

This could be easily fixed by also requiring a special query arg.

For example, in the RCP HS plugin I'm working on, I'm registering an endpoint and then only processing the request at that endpoint:

``` php
add_rewrite_endpoint( 'member', EP_PERMALINK | EP_PAGES );
......
global $wp_query;

if ( isset( $wp_query->query_vars[ 'member' ] ) ) {
    $plugin = new PW_RCP_Help_Scout_Plugin_Handler();

    echo json_encode( $plugin->getResponse() );

    exit();
}
```

In Helpscout, I set the URL of the app to `https://pippinsplugins.com/?member=1`.

It may be a little bit slower because more of WordPress is loaded, but at least it remains flexible.

**Comment by dannyvankooten** [comment]
Hey @pippinsplugins - missed this issue for some reason but you're right. Will setup a dedicated endpoint - will have too think about a way to make it backwards compatible though.. Any ideas

**Comment by dannyvankooten** [comment]
Took a stab at this in the above commit - running out of time now but will do some more testing tomorrow before releasing an update. :)

**Comment by pippinsplugins** [comment]
Looks great! I like the approach you took with asking people to update their URLs :+1:

**Comment by pippinsplugins** [comment]
Woot!

**Comment by pderksen** [comment]
v1.0.2 is now working great for me on both my sites using it. Thanks!

**Comment by dannyvankooten** [comment]
Great, thanks for confirming @pderksen!
