### ISSUE TITLE
Use edd_payment_gateways filter for readable gateway names

### ISSUE THREAD

**Issue by dannyvankooten** [webzunft/edd-helpscout#33]
So we see a prettier name for custom gateways.

![image](https://cloud.githubusercontent.com/assets/885856/13667617/90c3f54e-e6b7-11e5-9201-f70cd634b4f1.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by webzunft** [comment]
Seems to be less of a problem in `master`. Anyone using a gateway that still looks odd?
