### ISSUE TITLE
Deactivate license link in HS sends to blank page, doesn't deactivate license

### ISSUE THREAD

**Issue by bradley2083** [webzunft/edd-helpscout#43]
We've recently noticed that when the (deactivate) link is clicked in HelpScout, the link redirects to a new tab that's an empty page and then nothing happens (the license does not get deactivated in EDD).  Let me know if there is additional info I can provide to help debug. 

Thank you!

**Comment by bradley2083** [comment]
Just wanted to follow through on this issue to see if you've been able to replicate and if not, what else I can provide to help resolve the problem.  We are still seeing this issue when clicking "deactivate" from within HelpScout for customer licenses.  Thank you!

**Comment by flowdee** [comment]
Same here. This is how the final link looked like:

https://domain.com/edd-helpscout-api/deactivate_site_license?license_id=3346&site_url=customerwebsite.com%2F&s=JYxnYMDwNWDrtKeXAjG0YUCNON4%3D

**Comment by webzunft** [comment]
@flowdee thank you. Just to make sure: are you using the version from the `master` branch here or the wp.org version?

**Comment by flowdee** [comment]
Yep using Version 2.0-beta respectively the latest master branch from here. The issue still occurs.

**Comment by webzunft** [comment]
@flowdee thank you. Did you try the current master? I pushed a few updates yesterday, including one that prevented the links from working. Help Scout changed something a while ago.
If it is not fixed, does the same issue happen when you use the option to resend the payment receipt?

**Comment by flowdee** [comment]
Yes, when I posted my reply I made sure that the version is up2date with the one of this master.

**Comment by webzunft** [comment]
Thank you. Is there an error message?
Does the link to the client’s purchase and the license work?
I am running this on my own site as well and tested it just yesterday.

**Comment by flowdee** [comment]
HTTP ERROR 401

other links work fine

**Comment by webzunft** [comment]
Fixed with https://github.com/webzunft/edd-helpscout/commit/4582a2b6170e81ee579fa3bf092325d7830c4d95
