### ISSUE TITLE
PayPal Express payment link in HelpScout not working

### ISSUE THREAD

**Issue by markzahra** [webzunft/edd-helpscout#47]
On HelpScout it is no longer linking directly to the PayPal payment ever since we switched to PayPal Express, and that was a very handy feature to have.

**Comment by dannyvankooten** [comment]
Hi @markzahra,

What do the PayPal Express URL's look like, eg what is the URL when viewing a payment in PayPal?

**Comment by markzahra** [comment]
@dannyvankooten this is what we see in HelpScout: http://prntscr.com/e0q3l4

The URL to the payment from our website is as follows: 

https://history.paypal.com/cgi-bin/webscr?cmd=_history-details-from-hub&id=6HS7823220137613F

**Comment by markzahra** [comment]
@dannyvankooten any update on this issue please?

**Comment by dannyvankooten** [comment]
Hi @markzahra,

This should be fixed in the latest master here on Github. Can you test run that for me please?

**Comment by markzahra** [comment]
@dannyvankooten I downloaded a zip of the master from here. I then re-named the older plugin, uploaded this one, and tested again. HelpScout is now not showing any of the details. It only shows "No details found."

**Comment by markzahra** [comment]
@dannyvankooten Any thoughts on the above?

**Comment by webzunft** [comment]
@markzahra Not sure if this is still relevant to you. The master uses a different URL: `https://your-site.com/edd-helpscout-api/customer_info`. You would need to update it in your Help Scout App settings. Are you still using this plugin and would be willing to test it again?
