### ISSUE TITLE
Notes on multiple accounts

### ISSUE THREAD

**Issue by webzunft** [webzunft/edd-helpscout#51]
While working on removing the direct SQL query currently used to retrieve payments by email, I noticed that this becomes more complex when considering all possible scenarios.

An ideal scenario is that one user has one email address in Help Scout, one corresponding EDD Customer profile and one or more payments attached to that profile. We could easily use `EDD_Customer->get_payments()` to get all payments then.

The reality might look different, though. Here are a few possible scenarios:

* there are multiple emails in the Help Scout account from this user, each one attached to a different EDD customer account
* there are payments attached to the email address from Help Scout, but no corresponding EDD customer; maybe, because that email address was removed from the customer profile

A possible solution for this might look like this:

* retrieve the EDD customer for all emails in the Help Scout profile
* query payments for all EDD customers and list them grouped per customer in the Help Scout widget; that would also allow linking to each different EDD customer page
* query all payments not associated with any EDD customer account

**Comment by JJJ** [comment]
cc @kerijacoby for a support team perspective 👋

**Comment by webzunft** [comment]
Version 2.1 should handle most, if not all scenarios. I am closing this ticket until I become aware of something still missing.
