### ISSUE TITLE
Show multiple accounts

### ISSUE THREAD

**Issue by webzunft** [webzunft/edd-helpscout#52]
Related to https://github.com/dannyvankooten/edd-helpscout/issues/51 and might become obsolete with a major rewrite, but might be simpler to have this here first.

At the current state, the plugin can only find the EDD customer for the sending email address, not to the once also attached to the Help Scout profile.

We might want to query the EDD profiles for all attached emails and add a warning if there are more than one.

**Comment by pippinsplugins** [comment]
I would _love_ to see multiple emails / accounts supported.

**Comment by pderksen** [comment]
Same here.

**Comment by Spreeuw** [comment]
#63 Lists all profiles connected to the helpscout customer
