### ISSUE TITLE
Update query_customer_payments() for EDD 3.0 compatibility

### ISSUE THREAD

**Issue by ashleyfae** [webzunft/edd-helpscout#65]
This query needs updating to be compatible with EDD 3.0:

https://github.com/webzunft/edd-helpscout/blob/master/includes/class-endpoint.php#L202-L221

Optionally, the contents of `get_customer_orders()` _could_ be updated for improved performance in EDD 3.0: https://github.com/webzunft/edd-helpscout/blob/master/includes/class-endpoint.php#L247-L302 As is, once the actual customer payments query is updated `get_customer_orders()` should work perfectly fine, but there is a performance hit if you work with `EDD_Payment` instead of the new `Order` object in 3.0.

---

I (or someone else from the EDD team) will be happy to work up a PR for this soon, just getting the issue in. :+1:

**Comment by webzunft** [comment]
Thank you @ashleyfae. I would indeed appreciate if you could use your 3.0 insights to draft a PR
