### ISSUE TITLE
persist open/closed status of toggle sections

### ISSUE THREAD

**Issue by nosilver4u** [webzunft/edd-helpscout#74]
Currently Licenses always defaults to open, while Orders and Subscriptions remain closed. We often refer to Orders first, so it would be nice to have these sections make use of the persistence feature of HS widgets.

**Comment by nosilver4u** [comment]
I created a new pull request with a single commit in #78

**Comment by webzunft** [comment]
Thanks, @nosilver4u!

**Comment by webzunft** [comment]
Merged #78
