### ISSUE TITLE
License management link missing on some licenses?

### ISSUE THREAD

**Issue by nosilver4u** [webzunft/edd-helpscout#76]
I just noticed on my own account that several of the licenses do not have the nice little gear icon that lets us easily view/manage the license in EDD.
Looking at the code reveals that this link is dependent on the availability of price options: https://github.com/webzunft/edd-helpscout/blob/c3692c83c35d4ba62abc88e7bf617fd98816b13f/views/licenses.php#L19

That seems an odd choice, and we'd rather have the link there all the time. Any feedback on that?

**Comment by Terminator-Barbapapa** [comment]
If I remember correctly we've placed the gear icon there because there was too little room next to the license key.

**Comment by Spreeuw** [comment]
> If I remember correctly we've placed the gear icon there because there was too little room next to the license key.

but there's even less room for it on the bundled items 😬

**Comment by Terminator-Barbapapa** [comment]
I definitely remember there was a room issue. :)
Could indeed be that everything in one line got too crowded and we moved the tier and gear.

**Comment by webzunft** [comment]
Thanks to everyone involved!
