### ISSUE TITLE
Bring back Resend Receipt Link

### ISSUE THREAD

**Issue by webzunft** [webzunft/edd-helpscout#86]
https://github.com/webzunft/edd-helpscout/commit/4582a2b6170e81ee579fa3bf092325d7830c4d95#diff-62dbe9cdbba972e4e38c8d689e4d675a018328604057471191e8551d7c010cffL315-L316 removed the link that allows resending the receipt with one click.

There was no reason given in the description, so I guess this was an accident.

@Spreeuw do you remember if you removed the icon that resends purchase receipts on purpose?

@rene-hermenau thanks for making me aware of this!

**Comment by Spreeuw** [comment]
It never worked properly to begin with for me/us AFAIK!

**Comment by webzunft** [comment]
@Spreeuw thanks for your feedback. Would give it another try? The link would only work while you are logged in to your EDD site and have sufficient user rights. Maybe that was the problem?

**Comment by Spreeuw** [comment]
I guess that would indeed have been the problem. Our regular support staff don't have access to EDD, everything is handled with the information from the sidebar.
We don't need it in our workflow anyway, so whatever works for you is good for me 👍

**Comment by webzunft** [comment]
I talked to @rene-hermenau about this. He agrees that it does not make much sense if the button only works for logged-in users with the appropriate rights. That is not a big improvement since the link to the order details page is already given in the EDD widget.
